### ISSUE TITLE
Crash (Freeze) when skeleton fires arrow

### ISSUE THREAD

**Issue by loadstarnes** [Lemonszz/Ding-Dong#1]
Here is the exception:

```
[23:32:24] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:831) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:764) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:128) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NoSuchFieldError: field_1326
	at party.lemons.dingdong.DingDong.doDing(DingDong.java:15) ~[dingdong-1.1.0.jar:?]
	at net.minecraft.class_1665.handler$onProjectileHit$zbj000(class_1665.java:782) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	at net.minecraft.class_1665.method_7457(class_1665.java:386) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	at net.minecraft.class_1665.method_5773(class_1665.java:278) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	at net.minecraft.class_1667.method_5773(class_1667.java:99) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:580) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	at net.minecraft.class_3218$$Lambda$3213/538765486.accept(Unknown Source) ~[?:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:676) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:383) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:827) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.2+build.7.jar:?]
	... 4 more
```
This is the full log:
[2019-06-15-7.log](https://github.com/Lemonszz/Ding-Dong/files/3293810/2019-06-15-7.log)
This is the full crash report referenced by the log:
[crash-2019-06-15_23.32.24-server.txt](https://github.com/Lemonszz/Ding-Dong/files/3293812/crash-2019-06-15_23.32.24-server.txt)

Appreciate the mod, it seems like such a common sense, fun thing to have!

**Comment by lizfinite** [comment]
https://pastebin.com/3Mwa6itp

Seems this happens when any arrow is fired. The log above is me loading in, spawning the bow and arrow and crashing.
